name = "DrakanHex"
author = "alexyzer"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "751d871bdd07369768382036b62dbd134a9cf53d06c93851c66acf1dcf2e0b29"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
