name = "DrakanHex"
author = "alexyzer"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8dd8f04b35da3eb12756b205f4c98b0a9d23001a29331b79a297aa91bec714a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
