name = "DrakanHex"
author = "alexyzer"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7899dd3043dcb244df8063dbbaa7d20eb3757d8ab166efcb362445230993aa52"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
